a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'data.classes',
        'data.enemies',
        'data.items',
        'entities.character',
        'entities.player',
        'entities.enemy',
        'systems.combat',
        'systems.dungeon',
        'systems.inventory',
        'systems.quests',
        'systems.shop',
        'systems.skilltree',
        'utils.display',
        'utils.namegen',
        'utils.save_load',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='dungeons-of-aethoria',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    onefile=True,
)
